name = "ArbNumerics"
uuid = "7e558dbc-694d-5a72-987c-6f4ebed21442"
repo = "https://github.com/JeffreySarnoff/ArbNumerics.jl.git"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
