name = "ArbNumerics"
uuid = "7e558dbc-694d-5a72-987c-6f4ebed21442"
repo = "https://github.com/JeffreySarnoff/ArbNumerics.jl.git"
author = "Jeffrey Sarnoff"
license = "MIT"
version = "v0.4.1"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
GenericSVD = "01680d73-4ee2-5a08-a1aa-533608c188bb"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
Readables = "0d4725de-cd7c-5e44-8a85-a48caeef9fa5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
SpecialFunctions = ">=0.7.2"
BinDeps = ">=0.8.10"
GenericSVD = ">=0.2.1"
