name = "ArbNumerics"
uuid = "7e558dbc-694d-5a72-987c-6f4ebed21442"
repo = "https://github.com/JeffreySarnoff/ArbNumerics.jl.git"
keywords = ["math", "floating-point", "extended-precision", "accuracy", "precision"]
author = "Jeffrey Sarnoff"
license = "MIT"
version = "v1.2.4"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
GenericSVD = "01680d73-4ee2-5a08-a1aa-533608c188bb"
GenericSchur = "c145ed77-6b09-5dd9-b285-bf645a82121e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Readables = "0d4725de-cd7c-5e44-8a85-a48caeef9fa5"
GMP_jll = "781609d7-10c4-51f6-84f2-b8444358ff6d"
MPFR_jll = "3a97d323-0669-5f0c-9066-3539efd106a3"
FLINT_jll = "e134572f-a0d5-539d-bddf-3cad8db41a82"
Arb_jll = "d9960996-1013-53c9-9ba4-74a4155039c3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
SpecialFunctions = "0.7, 0.8, 0.9, 0.10, 1"
BinaryProvider = "0.4, 0.5, 0.6"
GenericSVD = "0.3"
GenericSchur = "0.4"
Readables = "0.3"
julia = "1"
